export const VALUE_TYPES = Object.freeze({
    BOOLEAN: 'BOOLEAN',
    DATE: 'DATE',
    DATETIME: 'DATETIME',
    EMAIL: 'EMAIL',
    FILE_RESOURCE: 'FILE_RESOURCE',
    IMAGE: 'IMAGE',
    INTEGER: 'INTEGER',
    INTEGER_NEGATIVE: 'INTEGER_NEGATIVE',
    INTEGER_POSITIVE: 'INTEGER_POSITIVE',
    INTEGER_ZERO_OR_POSITIVE: 'INTEGER_ZERO_OR_POSITIVE',
    LETTER: 'LETTER',
    LONG_TEXT: 'LONG_TEXT',
    NUMBER: 'NUMBER',
    PERCENTAGE: 'PERCENTAGE',
    PHONE_NUMBER: 'PHONE_NUMBER',
    TEXT: 'TEXT',
    TIME: 'TIME',
    TRUE_ONLY: 'TRUE_ONLY',
    UNIT_INTERVAL: 'UNIT_INTERVAL',
    URL: 'URL',
    // Value types not supported for aggregate data:
    // ORGANISATION_UNIT
    // TRACKER_ASSOCIATE
    // COORDINATE
    // USERNAME
    // AGE
})
