name: 'This workflow creates bill of material and uploads it to Dependency-Track each night'

on:
    schedule:
        - cron: '0 0 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    create-bom:
        uses: dhis2/workflows-platform/.github/workflows/generate-and-upload-bom.yml@pnpm
        with:
            node_version: 20
            project_id: '2437140f-8722-4dd4-a994-dcc48793b4ae'
        secrets: inherit
